env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - standard
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  # TypeScript でチェックされるため、 React のプロパティの型チェックはしない
  react/prop-types: off
  # prettier のチェックを error とする
  prettier/prettier:
    - error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': warn
