name: Node.js CI

# push をトリガーとしてビルドする
# push の内容がタグ付けだった時はリリースまで行う
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      # windows では改行コードが CRLF になってしまって prettier でエラーになるので
      # git で改行コードが CRLF にならないようにする
      - name: 改行コードを CRLF にしないように設定
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - uses: samuelmeuli/action-electron-builder@v1
        with:
          # secrets.GITHUB_TOKEN は特に設定しなくてもデフォルトで使えるらしい
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
