name: Node.js CI

on:
  push:
    branches: [ master ]

    strategy:
      matrix:
        os: [macOS-10.14, windows-2016]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run dist
      - name: いらない成果物を消す
        run: npx rimraf "dist/!(*.exe|*.deb|*.AppImage|*.dmg)"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist
